import { DEFAULT_TARGET_SUFFIX } from "./constants";

interface TargetInfo {
  name: string;
  arch: string;
  triple: string;
  sysroot: string;
  cxxInclude: string;
  cxxTripleInclude: string;
}

const ARCH_MAP: Record<string, string> = {
  aarch64: "aarch64-meego-linux-gnu",
  armv7hl: "armv7hl-meego-linux-gnueabi",
  i486: "i486-meego-linux-gnu",
};

/**
 * Derive target info from a target name like "SailfishOS-5.0.0.62-aarch64".
 */
export function resolveTarget(
  targetName: string,
  sdkTargetsDir: string,
): TargetInfo | undefined {
  const arch = targetName.split("-").pop();
  if (!arch || !ARCH_MAP[arch]) {
    return undefined;
  }

  const triple = ARCH_MAP[arch];
  const sysroot = `${sdkTargetsDir}/${targetName}${DEFAULT_TARGET_SUFFIX}`;

  return {
    name: targetName,
    arch,
    triple,
    sysroot,
    cxxInclude: `${sysroot}/opt/cross/${triple}/include/c++`,
    cxxTripleInclude: `${sysroot}/opt/cross/${triple}/include/c++`,
  };
}

/**
 * Discover the GCC version in the cross-compiler directory.
 * Returns the first directory name found (e.g. "10.3.1").
 */
export function findGccVersion(
  entries: string[],
  triple: string,
): string | undefined {
  return entries.find((e) => e !== triple && /^\d+/.test(e));
}

/**
 * Generate .clangd content for a Sailfish OS target.
 */
export function generateClangd(
  target: TargetInfo,
  gccVersion: string,
  qtModules: string[],
): string {
  const { sysroot, triple, cxxTripleInclude } = target;
  const qt5Base = `${sysroot}/usr/include/qt5`;

  const lines: string[] = [
    "# Sailfish OS — clangd configuration",
    "# Generated by sfdk-vscode",
    "",
    "CompileFlags:",
    "  Add:",
    "    - -xc++",
    "    - -std=c++14",
    `    - --target=${triple}`,
    `    - --sysroot=${sysroot}`,
    "    - -ferror-limit=0",
    "    - -Wno-everything",
    "    # GCC C++ standard library",
    "    - -isystem",
    `    - ${cxxTripleInclude}/${gccVersion}`,
    "    - -isystem",
    `    - ${cxxTripleInclude}/${gccVersion}/${triple}`,
    "    # Qt 5 headers",
    "    - -isystem",
    `    - ${qt5Base}`,
  ];

  for (const mod of qtModules.sort()) {
    lines.push("    - -isystem");
    lines.push(`    - ${qt5Base}/${mod}`);
  }

  lines.push(
    "    # Sailfish headers",
    "    - -isystem",
    `    - ${sysroot}/usr/include/sailfishapp`,
    "    # Qt module defines",
    "    - -DQT_CORE_LIB",
    "    - -DQT_GUI_LIB",
    "    - -DQT_QML_LIB",
    "    - -DQT_QUICK_LIB",
    "    - -DQT_NETWORK_LIB",
    "    - -DQT_SQL_LIB",
    "    - -DQT_CONCURRENT_LIB",
    "    - -DQT_DBUS_LIB",
    "    - -DQT_SVG_LIB",
    "    - -DQT_XML_LIB",
    "    - -DQT_WIDGETS_LIB",
    "    - -DQT_MULTIMEDIA_LIB",
    "  Remove:",
    "    - -m*",
    "",
    "# Suppress Qt 5 vs modern clang incompatibilities",
    "Diagnostics:",
    "  Suppress:",
    "    - expr_not_cce",
    "    - typecheck_invalid_operands",
    "    - typecheck_nonviable_condition",
    "    - ovl_no_viable_function_in_init",
    "",
  );

  return lines.join("\n");
}

/**
 * Generate .vscode/settings.json content for a Sailfish OS project.
 */
export function generateVscodeSettings(): string {
  return JSON.stringify(
    {
      "files.associations": {
        "*.qml": "qml",
        "*.js": "javascript",
        "*.pri": "qmake",
        "*.pro": "qmake",
        "*.ts": "xml",
        "*.spec": "rpm-spec",
      },
      "files.exclude": {
        "**/*.o": true,
        "**/moc_*.cpp": true,
        "**/qrc_*.cpp": true,
        Makefile: true,
        "documentation.list": true,
        ".qmake.stash": true,
      },
      "search.exclude": {
        "**/*.o": true,
        "**/moc_*.cpp": true,
        "**/qrc_*.cpp": true,
        "RPMS/**": true,
      },
    },
    null,
    4,
  );
}
